# Generated by Django 2.2.5 on 2020-01-09 16:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasteBinDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=264)),
                ('text', models.CharField(max_length=10000)),
            ],
            managers=[
                ('DBManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
